### ISSUE TITLE
Can not load pre-trained DETR model.

### ISSUE THREAD

**Issue by FXLYZ** [Scarecrow0/SGTR#8]
Hi,
it is a nice work! :)  But i can not load pre-trained DETR model.  Can you share a new pre-trained DETR model?
Thanks!

> Prepare Faster-RCNN Detector

    You can download the pretrained DETR on ResNet-101 we used in the paper:
        [VG](https://shanghaitecheducn-my.sharepoint.com/:u:/g/personal/lirj2_shanghaitech_edu_cn/EfJK_InTsk9Hq9RgXEui4gsBsk3pekuzPYk4gTR8coBYAA?e=fAo647),
        [OIv6](https://shanghaitecheducn-my.sharepoint.com/:u:/g/personal/lirj2_shanghaitech_edu_cn/Edrab9pd0O1NuVoz9RPmZtoBwxnSyl-NVIFCjxf6yUZ7FA?e=uPQZ1A),

    Unzip the checkpoint into the folder

    Then, you need to modify the pre-trained weight parameter MODEL.WEIGHTS in config.py playground/experiment/path/config_xx.py to the path of corresponding pre-trained detector weight to make sure you load the detection weight parameter correctly.

Error details:

> Traceback (most recent call last):
  File "/home/zztao/anaconda3/envs/sgtr/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/zztao/dev/SGTR/cvpods/engine/launch.py", line 118, in _distributed_worker
    main_func(*args)
  File "/home/zztao/dev/SGTR/tools/train_net.py", line 230, in main
    stage_main(args, config, build_model)
  File "/home/zztao/dev/SGTR/tools/train_net.py", line 155, in stage_main
    trainer.resume_or_load(resume=args.resume, load_mapping=cfg.MODEL.WEIGHTS_LOAD_MAPPING)
  File "/home/zztao/dev/SGTR/cvpods/engine/trainer.py", line 436, in resume_or_load
    self.start_iter = (self.checkpointer.resume_or_load(self.cfg.MODEL.WEIGHTS,
  File "/home/zztao/dev/SGTR/cvpods/checkpoint/checkpoint.py", line 170, in resume_or_load
    return self.load(path, load_mapping)
  File "/home/zztao/dev/SGTR/cvpods/checkpoint/checkpoint.py", line 107, in load
    checkpoint = self._load_file(path)
  File "/home/zztao/dev/SGTR/cvpods/checkpoint/detection_checkpoint.py", line 65, in _load_file
    loaded = super()._load_file(filename)  # load native pth checkpoint
  File "/home/zztao/dev/SGTR/cvpods/checkpoint/checkpoint.py", line 194, in _load_file
    return torch.load(f, map_location=torch.device("cpu"))
  File "/home/zztao/anaconda3/envs/sgtr/lib/python3.8/site-packages/torch/serialization.py", line 600, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/zztao/anaconda3/envs/sgtr/lib/python3.8/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by Scarecrow0** [comment]
It seems like the torch  load can not load the checkpoints.
It may be caused by a mismatched PyTorch version or trying to load a broken file.
https://discuss.pytorch.org/t/error-on-torch-load-pytorchstreamreader-failed/95103

May try to re-download the ckpt or check the version of pytorch.
